### ISSUE TITLE
Convertion failures

### ISSUE THREAD

**Issue by vncntprvst** [spyking-circus/spyking-circus#51] opened 2017-11-13 21:54 UTC
Hi,
I get an error when converting files after the main processing steps. The issue seems to be with opening the result files:
**File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write** 
Here's the full error output:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.6.2', 'console_scripts', 'spyking-circus-subtask')()
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\scripts\subtask.py", line 41, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\__init__.py", line 19, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\converting.py", line 263, in main
    N_tm = write_templates(output_path, params, extension)
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\converting.py", line 86, in write_templates
    templates       = io.load_data(params, 'templates', extension)
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\shared\files.py", line 619, in load_data
    'r', libver='latest').get('temp_x')[:].ravel()
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.6.2', 'console_scripts', 'spyking-circus')()
  File "c:\programdata\anaconda2\envs\spkc27\lib\site-packages\spyking_circus-0.6.2-py2.7.egg\circus\scripts\launch.py", line 354, in main
    subprocess.check_call(mpi_args)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpiexec', '-np', '1', 'spyking-circus-subtask', 'converting', 'D:\\Data\\Ephys\\031S_1103\\031S_1103_WR_MN_32Ch_nopp.dat', '1', '0', 'False', 'None']' returned non-zero exit status 1

Process exited with exit code 1`

**Comment by yger** [comment] 2017-11-14 09:53
Thanks for the feedback, as always, this should have been fixed in the master branch

**Comment by vncntprvst** [comment] 2017-11-14 20:04
Thanks for the quick fix, but unfortunately is still bugs: 
(it's a bit long, I'm sorry)
`-------------------------  Informations  -------------------------
| Exporting data for the phy GUI with 8 CPUs...
------------------------------------------------------------------
Do you want SpyKING CIRCUS to export PCs? (a)ll / (s)ome / (n)o
a
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    
    
    
load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    
    
load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
    
circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
    
    
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    
module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
    
    
write_pcs(output_path, params, extension, make_pcs)
write_pcs(output_path, params, extension, make_pcs)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
    
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
    
    
write_pcs(output_path, params, extension, make_pcs)
templates       = io.load_data(params, 'templates', extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
templates       = io.load_data(params, 'templates', extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
    
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
    
    
    
    
templates       = io.load_data(params, 'templates', extension)
'r', libver='latest').get('temp_x')[:].ravel()
'r', libver='latest').get('temp_x')[:].ravel()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
write_pcs(output_path, params, extension, make_pcs)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
    
    
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    
    
    
templates       = io.load_data(params, 'templates', extension)
fid = h5f.open(name, flags, fapl=fapl)
fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    'r', libver='latest').get('temp_x')[:].ravel()
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
IOError: 
IOError
Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
: 

Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    'r', libver='latest').get('temp_x')[:].ravel()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
    write_pcs(output_path, params, extension, make_pcs)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
    templates       = io.load_data(params, 'templates', extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
    'r', libver='latest').get('temp_x')[:].ravel()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
Traceback (most recent call last):
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
    write_pcs(output_path, params, extension, make_pcs)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
    templates       = io.load_data(params, 'templates', extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
    'r', libver='latest').get('temp_x')[:].ravel()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
IOError: 
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\scripts\subtask.py", line 41, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\__init__.py", line 19, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 308, in main
    write_pcs(output_path, params, extension, make_pcs)
Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\converting.py", line 140, in write_pcs
    templates       = io.load_data(params, 'templates', extension)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\circus\shared\files.py", line 619, in load_data
    'r', libver='latest').get('temp_x')[:].ravel()
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))`

**Comment by yger** [comment] 2017-11-15 07:07
On, I'll have one other look this morning. Since I can not reproduce the
error, sorry for the unsuccessful fix. However, I'm pretty sure, again,
that you are not using the right version: the line 619 where the error
appears in files.py  should not be the same in master branch, as I changed
it with last commit. So again, maybe several installs are messing around?

Le mar. 14 nov. 2017 à 21:04, Vincent Prevosto <notifications@github.com> a
écrit :

**Comment by vncntprvst** [comment] 2017-11-15 18:09
I cleaned up Conda directories manually, since conda and pip uninstalls were not thorough enough. 
I don't see the "line 619" error anymore, but I get this:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spkc27\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')()
  File "c:\code\spyking-circus\circus\scripts\subtask.py", line 41, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "c:\code\spyking-circus\circus\__init__.py", line 19, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "c:\code\spyking-circus\circus\converting.py", line 263, in main
    N_tm = write_templates(output_path, params, extension)
  File "c:\code\spyking-circus\circus\converting.py", line 86, in write_templates
    templates       = io.load_data(params, 'templates', extension)
  File "c:\code\spyking-circus\circus\shared\files.py", line 621, in load_data
    myfile = h5py.File(filename, 'r', libver='latest')
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))`

**Comment by yger** [comment] 2017-11-15 19:13
Hum... This is strange, as this given file is not open before the crash L86.... I can not  reproduce the bug, but I need to try with windows. Can you tell me more precisely:
- if you can reproduce it, even after relaunching everything (deleting the previous results)
- what is your h5py version (2.7.0 ?)

**Comment by vncntprvst** [comment] 2017-11-15 21:00
Ha, that did it. After deleting and relaunching all, the error disappeared. 
Pierre, I'm almost disappointed. I'll try to find a tougher bug for you to solve next time :)

For the record, the h5py version is 2.5 (`h5py=2.5.0=np19py27_2`). Conda seems to think this is the most up-to-date.

**Closed** 2017-11-15 21:01 UTC
