### ISSUE TITLE
problem with template fitting

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#323] opened 2020-11-30 15:39 UTC
Dear Pierre,
I have a question regarding template fitting. Some of the channels in my recording have high-amplitude spikes. Most of them (about 70%) are correctly put to one cluster, whereas the rest 30% are fitted with wrong template. To illustrate the problem:
the figure below has fragment of raw trace (peaks assigned to 2 different clusters are shown in red and blue):

![image](https://user-images.githubusercontent.com/58944642/100628806-49d45b80-3331-11eb-8d1f-61b4ebcd7279.png)

Templates, that were generated to fit these peaks:

![image](https://user-images.githubusercontent.com/58944642/100628977-74261900-3331-11eb-83be-dcbc75a8a47c.png)

As you can see shape and amplitude of red template has nothing to do with the peak it fitted to on the picture above.

And the results of such fitting:

![image](https://user-images.githubusercontent.com/58944642/100629164-a6377b00-3331-11eb-898c-9677a9d15e3d.png)

I tried to modify the following parameters without any success:
N_t : 2 or 3
spike_thresh: 5, 6 or 7
peaks: negative, positive, both
max_elts: 10000 or 20000
smart_search: True, False
merging_param: 2 or 1
sensitivity: 2 or 3
dispersion: 2, 2.5, 5
amp_limits: (0.3, 30), (0.3, 5), (0.8, 5), (1, 30), (0.8, 30)
merging: with or without

This behavior has been found on several channels/subjects. Could you help me to sort this issue out?

System:
Debian 10
Spyking Circus 1.0.4
Phy 2.0
32 channel 4-shank linear probe Neuronexus

Sincerely,
Stan

P.S. You can reproduce this with the data set I've sent you earlier; see e.g. channels 11 and 13.

**Comment by yger** [comment] 2020-11-30 15:59
Sure. Can I reproduce the problem with your small dataset? You are using the master branch?

**Comment by yger** [comment] 2020-11-30 16:09
And first, can you try to check with the branch 'mixtures' if you still see such a behavior? Use default param, you should not have to change anything here

**Comment by yger** [comment] 2020-11-30 16:11
Note also, as a side note, as the waveforms view is misleading: phy does not select isolated snippets. It can well be that you have single waveforms + some other active neurons, if both are always active together

**Comment by sv-bio** [comment] 2020-11-30 20:05
Dear PIerre,

Thanks for taking care of it.
1. Yes, this issue can be seen on the small data set, that I've sent to you, as well.
2. I am not sure, what the "branch mixtures" is and how to try it. Could you guide me with it?
3. I thought that if raw data are used (Ido not overwrite hence raw data (*.dat) file is created), then phy should show raw waveforms of a chosen cluster. Could you advice how to force Phy to show only spikes from selected cluster?

Sincerely,
Stan

**Comment by yger** [comment] 2020-11-30 20:22
>> pip install --upgrate https://github.com/spyking-circus/spyking-circus/archive/mixtures.zip

I meant that phy shows you snippets of the cluster, as you are saying, but do not make sure that the snippets are "isolated", i.e. that no other neurons are firing nearby. Keep in mind that with template matching, you can have linear sum of templates, so this can somehow bias a bit the Waveforrm view. But not to the extent you are saying

**Comment by sv-bio** [comment] 2020-11-30 22:11
Dear Pierre,

In order to install mixtures.zip I did:

$ source activate circus
(circus) $ pip install --upgrade https://github.com/spyking-circus/spyking-circus/archive/mixtures.zip

and got

Uninstalling spyking-circus-1.0.4:
      Successfully uninstalled spyking-circus-1.0.4
Successfully installed spyking-circus-refs-pull-317-head

Then I ran
spyking-circus /path/to/my/file/test.h5 -c 4

and it worked until I get the following:

Pre-computing the overlaps of templates...
100%|████████████████████████████████████|[00:01<00:00,  5.68it/s]
Traceback (most recent call last):
  File "/home/user/miniconda2/envs/circus/bin/spyking-circus-subtask", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/scripts/subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/clustering.py", line 1808, in main
    params, erase=True, normalize=templates_normalization, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu
  File "/home/user/miniconda2/envs/circus/lib/python3.6/site-packages/circus/shared/files.py", line 2282, in get_overlaps
    myfile2.create_dataset('version', data=numpy.array(version.split('.'), dtype=numpy.int32))
ValueError: invalid literal for int() with base 10: 'refs/pull/317/head'

Not sure, what shall I do next.

Sincerely,
Stan

**Comment by yger** [comment] 2020-12-01 05:36
sorry for that. Can you try to upgrade again? In fact, we switch to a new system, and it seems that the label is changing depending on how the software is installed... I usually use git directly, sorry for that

**Comment by sv-bio** [comment] 2020-12-01 23:54
Dear Pierre,
I upgraded the SC as you suggested. I modified .params file to specify probe map location and file format leaving the rest as is. Unfortunately, results looked similarly to the ones above. I also ran clustering on raw binary (float32) file format (the same fragment of data) and the results were worse than earlier (more channels without signals were considered as related to cluster, see image below).
![image](https://user-images.githubusercontent.com/58944642/100808835-8db48700-343d-11eb-8934-1120982cbeb1.png)

templates,  

![image](https://user-images.githubusercontent.com/58944642/100809000-e6841f80-343d-11eb-852e-5c1fe1363e8d.png)

and the result

![image](https://user-images.githubusercontent.com/58944642/100808897-b2a8fa00-343d-11eb-9423-690259b4d149.png)

**Comment by yger** [comment] 2020-12-02 04:49
I'll have one other look today. Is it a general behaviour or does it only happens for some templates? The template is localised on several channels or mostly one? If you want to try something, set templates_normalization to False in the [clustering] section. Let me know how it goes

**Comment by yger** [comment] 2020-12-02 05:44
forget my deleted post, normlization will be uneffective in this branch. I'll look into it today and provide you an answer. Just to be sure, most of the templates still do look normal, or is it a general behavior on the data?

**Comment by yger** [comment] 2020-12-02 08:36
And just to guide me, with your 5min long dataset, since I can not reproduce the problem or see any obvious mistakes in the phy GUI. Could you tell me what are the problematic templates, according to you? Or even send me the result folder, obtained on your machine? Because here everything seems nice and normal, at least on a first glimpse

**Comment by sv-bio** [comment] 2020-12-02 10:42
Dear Pierre,
Sure. I've sent the whole folder as zip archive to your e-mail.
Stan

**Comment by yger** [comment] 2020-12-02 11:46
This is what I can see for the templates you are pointing me, with phy and your data
![Capture d’écran de 2020-12-02 12-43-08](https://user-images.githubusercontent.com/1672447/100868619-21b53b80-349c-11eb-992b-30a321d69e64.png)

Or
![Capture d’écran de 2020-12-02 12-44-03](https://user-images.githubusercontent.com/1672447/100868632-27128600-349c-11eb-9e25-1102d321a9d1.png)

To me, this does not look problematic in fact.... 16 and 17 are distinct, and 30 and 32 should maybe be merged. You are plotting more waveforms with phy than I maybe? BUt even if the case, you can see that 16 and 17 are firing quite often close by, this is why the snippets of the small ones are "corrupted" by large ones spread around

**Comment by yger** [comment] 2020-12-02 11:49
And this is what I just obtained on my ran, so it seems compatible

![Capture d’écran de 2020-12-02 12-48-50](https://user-images.githubusercontent.com/1672447/100869067-c9326e00-349c-11eb-8643-c39f9353b17e.png)

Nothing problematic to me. Note also that what I did (in my run) and that you should do is to activate the remove_median option while filtering. This is common for in vivo recordings, and it will remove all common artefacts that will be present across all your channels (within shanks). Looks like you do have quite a lot of co-fluctuating channels, so this can helps to better appreciate the spikes

**Comment by sv-bio** [comment] 2020-12-02 23:16
Dear Pierre,

Thank you for sharing the results. I think, I found what is the problem: usually I visualize all the spikes of every cluster with waveform view, which produces figures that have much more noise, than if default value (100 spikes) is used. As you explained, waveform view of Phy is somewhat misleading, as it shows snippets, centred at min/max value (spike, fitted by a template) whereas side lobes may contain whatever other data, including spikes from another neurons (that are not considered in any further computations). This led me to think that many high-amplitude spikes (on a side lobes) were mis-classified as "noise".  Closer look at raw traces in with your comments in mind helped me to better understand what is actually shown by Phy. At the same time about 5% of high amplitude peaks of e.g. cluster 17 were mis-classified (as I shown earlier) that added more uncertainty to interpretation of waveform view and, overall, results. I agree, that **remove_median** could further refine result.
Pardon me for taking your time helping me to solve such an awkward problem.

Sincerely,
Stan

**Closed** 2020-12-02 23:17 UTC

**Comment by yger** [comment] 2020-12-04 09:27
no problem. In fact, if you are using windows (are you?) then I found a silent bug that could explain the difference between what I have on linux and what you might observe. Some templates could be contaminated by noise because of int overflow, so please upgrade to master, since this bug has been fixed.
