### ISSUE TITLE
Fitting fails with MPI error

### ISSUE THREAD

**Issue by MusicallyEternal** [spyking-circus/spyking-circus#76] opened 2018-05-23 13:24 UTC
Hello,

I am running spyking-circus 0.6.7 in a conda environment loaded on a cluster running CentOS/RHEL at my institute. I am analyzing a raw_binary dataset that I converted from a blackrock ns6 file. The cluster uses slurm to distribute tasks over multiple nodes and I have the miniconda version of mpi4py (3.0.0) and mpich (3.2.1) installed alongside spyking-circus in my conda environment. mpiexec --version yields the following:

> HYDRA build details:
    Version:                                 3.2.1
    Release Date:                            Fri Nov 10 20:21:01 CST 2017
    CC:                              gcc  -I/home/s.sridhar/miniconda2/envs/spiking/include  -m64  -Wl,-rpath,/home/s.sridhar/miniconda2/envs/spiking/lib -L/home/s.sridhar/miniconda2/envs/spiking/lib 
    CXX:                             g++  -I/home/s.sridhar/miniconda2/envs/spiking/include  -DBOOST_MATH_DISABLE_FLOAT128 -m64  -Wl,-rpath,/home/s.sridhar/miniconda2/envs/spiking/lib -L/home/s.sridhar/miniconda2/envs/spiking/lib 
    F77:                             gfortran   -Wl,-rpath,/home/s.sridhar/miniconda2/envs/spiking/lib -L/home/s.sridhar/miniconda2/envs/spiking/lib 
    F90:                             gfortran   -Wl,-rpath,/home/s.sridhar/miniconda2/envs/spiking/lib -L/home/s.sridhar/miniconda2/envs/spiking/lib 
    Configure options:                       '--disable-option-checking' '--prefix=/home/s.sridhar/miniconda2/envs/spiking' '--disable-dependency-tracking' '--enable-cxx' '--enable-fortran' 'CC=gcc' 'CFLAGS= -m64 -O2' 'LDFLAGS= -Wl,-rpath,/home/s.sridhar/miniconda2/envs/spiking/lib -L/home/s.sridhar/miniconda2/envs/spiking/lib' 'CPPFLAGS= -I/home/s.sridhar/miniconda2/envs/spiking/include -I/feedstock_root/build_artefacts/mpich_1520073382972/work/mpich-3.2.1/src/mpl/include -I/feedstock_root/build_artefacts/mpich_1520073382972/work/mpich-3.2.1/src/mpl/include -I/feedstock_root/build_artefacts/mpich_1520073382972/work/mpich-3.2.1/src/openpa/src -I/feedstock_root/build_artefacts/mpich_1520073382972/work/mpich-3.2.1/src/openpa/src -D_REENTRANT -I/feedstock_root/build_artefacts/mpich_1520073382972/work/mpich-3.2.1/src/mpi/romio/include' 'CXX=g++' 'CXXFLAGS= -DBOOST_MATH_DISABLE_FLOAT128 -m64 -O2' '--cache-file=/dev/null' '--srcdir=.' 'LIBS=-lpthread ' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select

I encounter an error during the fitting phase of the analysis. A small part of the error is given here:

> Traceback (most recent call last):
  File "/home/s.sridhar/miniconda2/envs/spiking/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.6.7', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/site-packages/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/site-packages/circus/fitting.py", line 134, in main
    c_overs    = io.load_data_memshared(params, 'overlaps')
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/site-packages/circus/shared/files.py", line 501, in load_data_memshared
    win_indices = MPI.Win.Allocate_shared(indices_bytes, intsize, comm=sub_comm)
  File "mpi4py/MPI/Win.pyx", line 101, in mpi4py.MPI.Win.Allocate_shared
mpi4py.MPI.Exception: Other MPI error, error stack:
PMPI_Win_allocate_shared(162).......: MPI_Win_allocate_shared(size=0, MPI_INFO_NULL, comm=0x84000002, baseptr=0x7fff9a10b810, win=0x7f0b8bc45ad8) failed
MPID_Win_allocate_shared(208).......:
win_init(276).......................:
MPIR_Comm_dup_impl(57)..............:
MPIR_Comm_copy(739).................:
MPIR_Get_contextid_sparse_group(614): Too many communicators (0/2048 free on this process; ignore_id=0)
Traceback (most recent call last):
  File "/home/s.sridhar/miniconda2/envs/spiking/bin/spyking-circus", line 11, in <module>
    load_entry_point('spyking-circus==0.6.7', 'console_scripts', 'spyking-circus')()
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/site-packages/circus/scripts/launch.py", line 364, in main
    subprocess.check_call(mpi_args)
  File "/home/s.sridhar/miniconda2/envs/spiking/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpiexec', '-np', '24', 'spyking-circus-subtask', 'fitting', '/tmp/i140703-001.dat', '24', '0', 'False']' returned non-zero exit status 1.

The entire error output was much longer, but was basically the above error repeated several times. I have attached the spyking-circus output along with the error output as text files, if you need them. [i1407003-001-err.txt](https://github.com/spyking-circus/spyking-circus/files/2031195/i1407003-001-err.txt)
[i1407003-001-out.txt](https://github.com/spyking-circus/spyking-circus/files/2031196/i1407003-001-out.txt) It looks like the error is in MPI, with the message "Too many communicators ...".

Any idea what is going on and how to fix it?

**Comment by yger** [comment] 2018-05-24 08:57
Dear Sridhar

Thanks for reporting the issue. In fact, I have no idea about why such an
error could appear. I know that one user had a similar problem a while ago,
but then I don't know how it has been fixed. Problem is that I can not
reproduce the error, and it seems to be related to MPI itself. Do you see
the same behavior if you are using less cores?
I'll keep you updated if I find anything

Best

Pierre

Le mer. 23 mai 2018 à 15:24, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by yger** [comment] 2018-05-24 09:06
Otherwise, an option (but I don't know if this is possible) would be to grant me an access on the machine, such that I can reproduce the error and troubleshoot what is going on with MPI. Meanwhile, I'll try to ask our users if somebody encountered and solved this issue

**Comment by MusicallyEternal** [comment] 2018-05-24 15:06
Hey Pierre,

Thank you for the quick response. 

I see the same behaviour when using just one core as well. I also asked others at my institute who know MPI a little better and we're trying different solutions. If it helps, we realised that spyking circus was making full use of all the requested cores until it reached the fitting stage. It fails only when it hits the fitting stage. I'll keep you posted about any solutions we find.

Also, I am sorry, but it won't be possible to grant you access to the machine. I asked and the answer was a simple no :/ If there are specific things you think I could try, do let me. I'd be happy to help!

Cheers,
Shash

**Comment by yger** [comment] 2018-05-24 15:29
If you find a solution, I will be very happy.. I can explain you more in
details what the code is doing, if needed, but basically at this stage, it
is loading once per physical machine the templates and overlaps, such that
every processes on the machines have a shared view of the memory. This is
reducing quite a lot the memory usage. But in your case, worst case
scenario, this option could be turned off..  As said, I sent a mail to
users that also had this error at some point, asking if and how they solved
it. I'll let you know while trying to read the code one more time. The
weird part is that the function where this crash is happening is also
called, before, during the clustering stage. And as you are telling me, it
worked. I'm suspecting some MPI object (communicators) are not properly
destroyed/closed in the code, but I don't know where, and not every MPI
implementation seems to display the issue..

For the SSH access to the cluster, I was asking in order to know if I could
help, but the negative response was expected. I was assuming it would be
the standard policy for IT security to ban remote accesses.

Best

Pierre

Le jeu. 24 mai 2018 à 17:06, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by yger** [comment] 2018-05-25 06:26
The only answer I got so far from a user is that they changed OS (and maybe MPI), and the error disappeared. I'll keep digging

**Comment by MusicallyEternal** [comment] 2018-05-25 13:47
Hey Pierre, 

Most of our attempts at fixing the problem haven't been successful so far. We are not entirely sure if the error has something to do with our implementation of MPI and there is a significant chance the problem lies there. The system is a few years old and the packages aren't all up to date. A system revamp is planned in the coming few months, and the hope is that things will then work better/more reliably. Even then, I'd like to try a little longer before I give up.

I scanned through the code, and found the parameter called SHARED_MEMORY that you import from .shared.mpi in file "fitting.py". Is that the parameter you're talking about disabling? Simply setting it to False after importing should do the job, temporarily, right? 

I have been following the thread that you're referring to (on google groups). Lets hope George responds to the thread as well, and that he figured out a solution.

The good thing is, I've got spyking-circus to run on my laptop. Albeit much slower than the cluster, it works well. Until I get it running on the cluster, I'll continue using it on my laptop. There's one thing though - on my laptop (Ubuntu 16.04), it was throwing up an error during the clustering phase while using mpi4py version 3.2.1. The error disappeared when I downgraded mpi4py to version 2.0.0. I tried the same tactic in my conda environment on the cluster, but without success. I currently need to start working on data (I've spent much of this week trying to get spyking circus to work), so if you think it's worth filing a bug report for the mpi4py 3.2.1 error, I'll do it, but I won't be able to try things as rapidly on my laptop since it takes an hour per run to reproduce/encounter an error.

Thanks for the good work on spyking-circus, btw :) I hope this nagging mpi issue resolves itself soon!

Cheers,
Shash

**Comment by yger** [comment] 2018-05-25 14:02
Yes, if this parameter SHARED_MEMORY is set to False, then the code 
should work for you. I will do a commit in the master branch such that 
this parameter can be an option in the configuration file (activated by 
default, but could be manually set to False). I also discovered that 
mpi4py 3.0.0 seems to have some issues, at least reported by mac users, 
so I'll try to fix that asap. Don't waste time with bug reports :-)

Best

Pierre


Le 25/05/2018 à 15:47, Shashwat Sridhar a écrit :

**Comment by MusicallyEternal** [comment] 2018-05-25 14:11
Thanks a lot! I'll try this out once the new code is up. I won't be near my laptop over the weekend, so I'll either try this tonight or, most probably, on Monday.

Cheers,
Shash

**Comment by yger** [comment] 2018-05-25 15:08
I created a branch shared_mem where you should be able to turn off shared
memory by adding the following parameter in the [data] section of the
configuration file
shared_memory = False

I'll merge it soon with the master branch, once I've tested everything

Le ven. 25 mai 2018 à 16:11, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by MusicallyEternal** [comment] 2018-05-30 11:31
Okay, fantastic news :)
Disabling shared_memory solved the problem and I am now able to run spyking-circus on multiple nodes on the cluster at my institute. The analysis on around 48 nodes take close to 15 minutes to complete for a 12min recording. Thank you so much for the help!

**Closed** 2018-06-01 15:54 UTC
