### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#275] opened 2020-07-21 05:44 UTC
Spyking-circus throws this error on me. Any idea why? Also, its hanging indefinitely rather than aborting.

```
-------------------------  Informations  -------------------------
| Number of spikes fitted : 25141822
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Automatic merging with a threshold of 0.75
------------------------------------------------------------------
Updating the data...
100%|████████████████████████████████████|[03:54<00:00, 13.79s/it]
Deleting 0 noisy templates
Updating the data...
100%|████████████████████████████████████|[03:57<00:00, 13.99s/it]
Updating the data...
100%|████████████████████████████████████|[03:44<00:00, 13.21s/it]
Traceback (most recent call last):
  File "/data/code/python/chuck-miniconda/envs/circus/bin/spyking-circus-subtask", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-subtask')())
  File "/data/multimem/code/spyking-circus/build/lib/circus/scripts/subtask.py", line 53, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu, extension=extension)
  File "/data/multimem/code/spyking-circus/build/lib/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu, extension)
  File "/data/multimem/code/spyking-circus/build/lib/circus/merging.py", line 76, in main
    _ = gui.MergeWindow(params, app, extension_in, extension_out)
  File "/data/multimem/code/spyking-circus/build/lib/circus/shared/gui.py", line 397, in __init__
    self.finalize(None)
  File "/data/multimem/code/spyking-circus/build/lib/circus/shared/gui.py", line 1451, in finalize
    slice_clusters(self.params, self.clusters, to_merge=self.all_merges, to_remove=list(self.to_delete), extension=self.ext_out, light=True)
  File "/data/multimem/code/spyking-circus/build/lib/circus/shared/algorithms.py", line 632, in slice_clusters
    result['electrodes'] = numpy.delete(result['electrodes'], numpy.unique(to_delete))
  File "<__array_function__ internals>", line 6, in delete
  File "/data/code/python/chuck-miniconda/envs/circus/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by yger** [comment] 2020-07-24 08:36
I pushed a fix that maybe will solve this problem. Most likely, this is because of float/int in the array, so broadcasting the type to int may do the job

**Comment by holmescharles** [comment] 2020-08-10 00:25
Now I'm getting this error:

```
Analyzing data to get whitening matrices and thresholds...
Found 26.1794s to compute the whitening matrix...
Because of whitening, need to recompute the thresholds...
Searching spikes to construct the PCA basis...
100%|████████████████████████████████████|[00:31<00:00,  7.75s/it]
Found 30396 waveforms over 30396 requested
Searching isolated random spikes to sample amplitudes...
100%|████████████████████████████████████|[00:42<00:00, 10.72s/it]
Found 303996 spikes over 303996 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|████████████████████████████████████|[00:55<00:00, 13.84s/it]
Found 303996 isolated spikes over 303996 requested (147244 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|████████████████████████████████████|[00:42<00:00, 10.67s/it]
Found 303996 spikes over 303996 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|████████████████████████████████████|[00:49<00:00, 12.38s/it]
Found 303996 spikes over 303996 requested
Refining density estimations...
Running density-based clustering...
  0%|                                            |[04:23<?, ?it/s]
Traceback (most recent call last):
  File "/data/multimem/chuck/miniconda3/envs/circus/bin/spyking-circus-subtask", line
33, in <module>
    sys.exit(load_entry_point('spyking-circus', 'console_scripts', 'spyking-circus-sub
task')())
  File "/data/multimem/code/spyking-circus/build/lib/circus/scripts/subtask.py", line
55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/data/multimem/code/spyking-circus/build/lib/circus/__init__.py", line 23, in
launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/data/multimem/code/spyking-circus/build/lib/circus/clustering.py", line 1135,
 in main
    c = numpy.delete(c, to_remove)  # update the cluster labels
  File "<__array_function__ internals>", line 6, in delete
  File "/data/multimem/chuck/miniconda3/envs/circus/lib/python3.6/site-packages/numpy/
lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 0 is out of bounds for axis 0 with size 0
^CTraceback (most recent call last):
```

**Comment by holmescharles** [comment] 2020-08-10 02:12
I am getting a similar issue with the release version:

```
Running density-based clustering...
100%|███████████████████████████████████|[19:17<00:00, 289.32s/it]




Traceback (most recent call last):
  File "/data/multimem/chuck/miniconda3/envs/circus-release/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.9.9', 'console_scripts', 'spyking-circus-subtask')()
  File "/data/multimem/chuck/miniconda3/envs/circus-release/lib/python3.6/site-packages/circus/scripts/subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/data/multimem/chuck/miniconda3/envs/circus-release/lib/python3.6/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/data/multimem/chuck/miniconda3/envs/circus-release/lib/python3.6/site-packages/circus/clustering.py", line 1130, in main
    c = numpy.delete(c, to_remove)  # update the cluster labels
  File "<__array_function__ internals>", line 6, in delete
  File "/data/multimem/chuck/miniconda3/envs/circus-release/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by yger** [comment] 2020-08-19 05:21
I'll have a look when back from holidays, end of the month. Can you share the dataset with me?

**Comment by yger** [comment] 2020-08-25 15:00
I made a putative patch in master, trying to understand and reproduce the problem. Can you tell me if this is working?

**Comment by yger** [comment] 2020-09-04 11:15
Solved in master branch

**Closed by yger** 2020-09-04 11:15 UTC
